[package]
name = "dsd-melonds"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]
name = "dsd_melonds_rs"

[dependencies]
anyhow = "1.0"
cxx = "1.0"
# ds-decomp = "0.9"
ds-decomp = { git = "https://github.com/AetiasHax/ds-decomp.git" }

[build-dependencies]
cxx-build = "1.0"
